name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - run: ls -l
    - run: pwd
    - run: dotnet restore /home/runner/work/dbda/dbda/dotnet_core/basic_app
    - run: dotnet build /home/runner/work/dbda/dbda/dotnet_core/basic_app
    - run: ls -l /home/runner/work/dbda/dbda/dotnet_core/basic_app
    # dotnet build and publish
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    #- name: dotnet publish
    #  run: |
    #    dotnet publish -c Release -o dotnetcorewebapp 
    
