name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ASP.NET 5.0 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101' # Check for latest at link at .NET 5 download page
      - run: dotnet build /home/runner/work/dbda/dbda/dotnet_core/basic_app
      - run: dotnet test /home/runner/work/dbda/dbda/dotnet_core/basic_app
      - run: ls -l
      - run: ls -l /home/runner/work/dbda/dbda/dotnet_core/basic_app
    # dotnet build and publish
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    #- name: dotnet publish
    #  run: |
    #    dotnet publish -c Release -o dotnetcorewebapp 
    
