# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Checkout_Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout repo:inte_pycode
      uses: actions/checkout@v2
      with:
        repository: VishKapare10/inte_pycode
        token: ${{ secrets.DEC18_TOKEN }} # 'DEC18_token' is a secret that contains your PAT
        path: .
    - name: list out
      run: ls -l
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install ansible
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run code
      run: python3 hello-world-docker-action/random_no_gen.py
