# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: checkout_workflow21

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: checkout_21
        path: ./dbda
    - name: Checkout repo:inte_pycode
      uses: actions/checkout@v2
      with:
       repository: VishKapare10/inte_pycode
       token: ${{ secrets.DEC18_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
       path: ./inte_pycode

    - name: list-out
      run: ls -l
    
    - name: list dbda
      run: ls dbda
    - name: list inte_pycode
      run: ls inte_pycode
    - name: copy files
      run: cp -r inte_pycode ./dbda/dbda_docker_action
    - name: listout dir
      run: ls ./dbda/dbda_docker_action
    - name: build_and_run
      uses: ./dbda/dbda_docker_action # Uses an action in the specified directory
      id: build_and_run
