name: 'artifacts_cleanup'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.for_webhooks }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v1
          tag_name: v1
