# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docker_CICD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup_and_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install ansible
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test the python code
      run: find . -name "*.py" | xargs -n 1 python3 
      
    - name: Test playbook
      run: ansible-playbook code/debug_msg.yml
      
  build:
    if: ${{ success() }} && ${{ github.event_name == 'push' }}
    needs: setup_and_run
    runs-on: ubuntu-latest
    steps:
    - name: Display event name on which job is triggered
      run: echo Event name:${{ github.event_name }}
      
    - uses: actions/checkout@v2
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: vishkapare10/docker-test
        tags: git_cicd_base
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
