  
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python-Ansible-Artifact-Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install ansible
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    
    - name: Test the python code
      run: python3 ./python_practice/dict_use_case.py
      
    - name: Test playbook
      run: ansible-playbook code/debug_msg.yml
        
    - name: Build project # This would actually build your project, using zip for an example artifact
      run: |
          zip dbda_artifact."$BUILD_NUMBER".zip code/*
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: v1_dec28
          release_name: dbda_release_2feb
          version: v1
          draft: false
          prerelease: false   
          
    - name: Prepare artifact metadata
      id: prepare_artifact_metadata
      run: |
        echo ::set-output name=ARTIFACT_PATH::./dbda_artifact."$BUILD_NUMBER".zip
        
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_PATH }}
          asset_name: artifact_after_failure.${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_PATH }}
          asset_content_type: application/zip
