# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: dec20_checkout_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout

    - name: Checkout repo:inte_pycode
      uses: actions/checkout@v2
      with:
       repository: VishKapare10/inte_pycode
       token: ${{ secrets.DEC18_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
       path: .
    
    - name: list-out
      run: ls -l
