# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Download_release_workflow
on: push
jobs:
  build:
    name: "Download release"
    runs-on: ubuntu-latest
    steps:
    - name: Download CLI
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: VishKapare10/dbda
        tag: 'refs/heads/master'
        path: downloads
        file: dbda-dec29.rpm
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: list-out
      run: |
        ls -l downloads
        cd downloads
        rpm -Uvh  dbda-dec29.rpm
        ls -al /opt/dbda
