name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./dbda
      
    - name: list-out
      run: |
         ls -l
          
    - name: rpm_build
      id: rpm_build
      run: |
        mkdir -p rpmbuild/BUILD rpmbuild/BUILDROOT rpmbuild/RPMS rpmbuild/SOURCES rpmbuild/SPECS rpmbuild/SRPMS
        cp -r dbda rpmbuild/
        cp dbda/dbda.spec rpmbuild/SPECS
        cd rpmbuild
        tar -cf dbda.tar.gz dbda
        ls -l
        rpmbuild -bb -v dbda.spec
        ls -l /home/runner/rpmbuild/RPMS/x86_64
