name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
              
    - name: setup-devtree and build rpm
      run: |
        mkdir -p rpmbuild/BUILD rpmbuild/BUILDROOT rpmbuild/RPMS rpmbuild/SOURCES rpmbuild/SPECS rpmbuild/SRPMS
        tar -cf dbda.tar.gz ./code
        mv dbda.tar.gz /home/runner/rpmbuild/SOURCES
        ls -l
        pwd
        rpmbuild -ba -v ./dbda.spec
        ls /home/runner/rpmbuild/SRPMS
