name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./dbda

    - name: list-out
      run: ls -l
    
    - name: Create tar file
      run: tar -cf dbda.tar.gz ./dbda
      
    - name: build rpm package
      run: rpmdev-setuptree && rpmbuild -ba dbda/dbda.spec
      
    - name: list-out
      run: ls -l
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
