name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./dbda

    - name: list-out
      run: ls -l
    
    - name: setup-devtree
      run: |
        mkdir -p rpmbuild/BUILD rpmbuild/BUILDROOT rpmbuild/RPMS rpmbuild/SOURCES rpmbuild/SPECS rpmbuild/SRPMS
        tar -cf /home/runner/rpmbuild/SOURCES/dbda.tar.gz dbda
        rpmbuild -ba dbda/dbda.spec
         
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
