name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./dbda
      
    - name: list-out
      run: |
         ls -l 
         ls -l ./repo
          
    - name: rpm_build
      id: rpm_build
      run: |
        mkdir -p /home/runner/rpmbuild/SOURCES
        tar -cf dbda.tar.gz ./dbda
        ls -l
        cp dbda.tar.gz /home/runner/rpmbuild/SOURCES
        rpmbuild -bb -v ./dbda/dbda.spec
        ls -l /home/runner/rpmbuild/RPMS/x86_64
   
