name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./repo
              
    - name: setup-devtree and build rpm
      run: |
        mkdir -p /home/runner/rpmbuild/SOURCES
        tar -cf dbda.tar.gz ./repo
        ls -l
        cp dbda.tar.gz /home/runner/rpmbuild/SOURCES
        rpmbuild -ba -v ./repo/dbda.spec
        ls -l /home/runner/rpmbuild/SRPMS
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: ${{ /home/runner/rpmbuild/SRPMS }}
