name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./repo
          
    - name: rpm_build
      id: rpm_build
      run: |
        mkdir -p /home/runner/rpmbuild/SOURCES
        tar -cf dbda.tar.gz ./repo
        ls -l
        cp dbda.tar.gz /home/runner/rpmbuild/SOURCES
        rpmbuild -bb -v ./repo/dbda.spec
        ls -l /home/runner/rpmbuild/RPMS
