name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./dbda
          
    - name: setup-devtree and build rpm
      run: |
        mkdir -p rpmbuild/BUILD rpmbuild/BUILDROOT rpmbuild/RPMS rpmbuild/SOURCES rpmbuild/SPECS rpmbuild/SRPMS
        tar -cf dbda.tar.gz ./dbda
        mv dbda.tar.gz ./rpmbuild/SOURCES
        rpmbuild -bb -v ./dbda/dbda.spec
        mv -r rpmbuild/SRPMS .
        ls -l
