name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
              
    - name: setup-devtree and build rpm
      run: |
        mkdir -p rpmbuild/BUILD rpmbuild/BUILDROOT rpmbuild/RPMS rpmbuild/SOURCES rpmbuild/SPECS rpmbuild/SRPMS
        ls -l
        pwd
        rpmbuild -ba -v ./dbda.spec
        ls -l rpmbuild/SRPMS
